# Generated by Django 5.2.4 on 2025-07-07 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("designs", "0002_alter_design_status"),
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("processing", "Processing"),
                            ("in_production", "In Production"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled_customer", "Cancelled by Customer"),
                            ("cancelled_manufacturer", "Cancelled by Manufacturer"),
                        ],
                        default="pending_payment",
                        max_length=30,
                    ),
                ),
                (
                    "order_total_price_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("shipping_address", models.JSONField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_carrier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_created_from",
                        to="quotes.quote",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="designs.design",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "manufacturer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "Orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["customer"], name="Orders_custome_2ff3cc_idx"),
                    models.Index(
                        fields=["manufacturer"], name="Orders_manufac_9c9631_idx"
                    ),
                    models.Index(fields=["status"], name="Orders_status_3bf286_idx"),
                ],
            },
        ),
    ]
