# Generated by Django 5.2.4 on 2025-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="actual_ship_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_manuf_confirm", "Pending Manufacturer Confirmation"),
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("in_production", "In Production"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("cancelled_customer", "Cancelled by Customer"),
                    ("cancelled_manufacturer", "Cancelled by Manufacturer"),
                ],
                default="pending_manuf_confirm",
                max_length=30,
            ),
        ),
    ]
