# Generated by Django 5.2.4 on 2025-07-06 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="manufacturer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("capabilities", models.JSONField(blank=True, null=True)),
                (
                    "certifications",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("website_url", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "db_table": "Manufacturers",
            },
        ),
    ]
