# Generated by Django 5.2.4 on 2025-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="markup_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="General markup factor applied to total cost (e.g., 1.2 for 20% markup).",
                max_digits=5,
            ),
        ),
    ]
