# Generated by Django 5.2.4 on 2025-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='about',
            field=models.TextField(blank=True, help_text='Short bio or description of the manufacturer.', null=True),
        ),
    ]
