# Generated by Django 5.2.4 on 2025-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manufacturer_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='background_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='portfolio_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
