export * from '../components'; // re-export all components as pages for now
export * from './LandingPage';
export * from './LoginPage';
export * from './LoginPage/LoginRoleSelector';
export * from './SignupPage/SignupRoleSelector';
export * from './SignupPage/CustomerSignupPage';
export * from './SignupPage/ManufacturerSignupPage';
export * from './ManufacturerDashboard';
export * from './CustomerDashboard';
export * from './ManufacturerDirectoryPage';
export * from './ManufacturerProfilePage';
export * from './TrustAndSecurityPage';
export * from './AboutUsPage';
export * from './ContactPage';
export * from './FAQPage';
export * from './LegalPage';
export * from './HowItWorksDetailedPage';
export * from './DesignQuotationsPage';
export * from './UploadPage';
