# Generated by Django 5.2.4 on 2025-07-06 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("design_name", models.CharField(max_length=255)),
                ("s3_file_key", models.CharField(max_length=1024)),
                ("material", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_analysis", "Pending Analysis"),
                            ("analysis_complete", "Analysis Complete"),
                            ("quoted", "Quoted"),
                            ("ordered", "Ordered"),
                        ],
                        default="pending_analysis",
                        max_length=20,
                    ),
                ),
                ("geometric_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Design",
                "verbose_name_plural": "Designs",
                "db_table": "Designs",
                "ordering": ["-created_at"],
            },
        ),
    ]
