# Generated by Django 5.2.4 on 2025-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_design_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='inspection_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='packaging_requirements',
            field=models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom / Branded'), ('export', 'Export (Crate/Fumigated)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='design',
            name='requires_engineering_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='urgency',
            field=models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent')], default='standard', max_length=20),
        ),
    ]
