# Generated by Django 5.2.4 on 2025-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_inspection_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='additional_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='design',
            name='manufacturing_process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='post_processing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='required_certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='design',
            name='shipping_destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='design',
            name='supporting_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='surface_finish',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's target price per part", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='tolerances',
            field=models.TextField(blank=True, default=''),
        ),
    ]
