# Generated by Django 5.2.4 on 2026-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_design_additional_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Flag indicating if this design is for internal assessment only.'),
        ),
    ]
