# Generated by Django 5.2.4 on 2025-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_actual_ship_date_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_manuf_confirm', 'Pending Manufacturer Confirmation'), ('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('payment_failed', 'Payment Failed'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled_customer', 'Cancelled by Customer'), ('cancelled_manufacturer', 'Cancelled by Manufacturer')], default='pending_payment', max_length=30),
        ),
    ]
